### ISSUE TITLE
Alignify needs to recognise pre-existing ampersand separators

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/MarkdownShortcutsForSE#14]
For example:
```
A &-> B
```

<kbd>alt</kbd> + <kbd>e</kbd>

```
\ce{A &-> B}
```

<kbd>alt</kbd> + <kbd>a</kbd>

```
\begin{align}
\ce{A &-&> B}
\end{align}
```
where is should be

```
\begin{align}
\ce{A &-> B}
\end{align}
```

Not exactly sure what went wrong and where...

**Comment by GaurangTandon** [comment]
Thanks for your report. Fixed in v1.6.0.

Test case:

```
A = B = C
E=1
C6=H12
A <= 1
\ce{C6=H12 -> Pt}
\ce{C6=H12 &<=> Pt}
```

Expected output:

```
\begin{align}
A &= B = C\\
E&=1\\
C6&=H12\\
A &<= 1\\
\ce{C6=H12 &-> Pt}\\
\ce{C6=H12 &<=> Pt}
\end{align}
```

Features tested:

1. aligning simple math equations (only the first = sign considered)
2. considering = as normal equality outside `\ce`, not touching it inside `\ce` when surrounded on both sides by alphabet/number/<
3. not applying `&` (like `&&->`) if it already exists there
