### ISSUE TITLE
dollarify + double dollarify = triple dollarify

### ISSUE THREAD

**Issue by polyluxus** [GaurangTandon/MarkdownShortcutsForSE#4]
If  
A, mark,  <kbd>Alt</kbd>+<kbd>z</kbd>, <kbd>Alt</kbd>+<kbd>c</kbd> => `$$$A$$$`  
which should ideally only insert another dollarify  
A, mark,  <kbd>Alt</kbd>+<kbd>z</kbd>, <kbd>Alt</kbd>+<kbd>c</kbd> => `$$A$$`  

The other way around works well  
A, mark,  <kbd>Alt</kbd>+<kbd>c</kbd>, <kbd>Alt</kbd>+<kbd>z</kbd> => `$A$`  
as it removes a set of dollar signs.

**Comment by GaurangTandon** [comment]
Sure, valid problem.

Now, I may  match the unwrapping by watching the keystrokes. But then if you dollarify `A` into `$A$`, and then type some other text somewhere else, and then return to `$A$` to undo the dollarfication, it would not work (when it should).

So, the second solution is to arrange the given sequence of the wrapper characters in chronological order, so that `$` would come before `$$`, and then perform the unwrapping stuff by matching from right to left. That is doable :) I'll try it soon.

**Comment by GaurangTandon** [comment]
I tried this out. The problem is that - by the proposed logic - it is impossible to unwrap a single dollar sign after two or more dollar signs have been inserted. By the proposed logic, pressing Alt-Z in the following case `$$|A|$$`  should insert another `$` pair to make `$$$|A|$$$`.

However, what if there are already three dollar signs like `$$$|A|$$$` now it would to insert another single dollar pair.

The next update I'll try fix this by counting number of `$` pairs on either side. If it is odd, we unwrap a single dollar pair, and if it is even, we insert it.

**Comment by polyluxus** [comment]
Why would one ever need more than two dollar signs? That doesn't even produce valid MathJax code. There should never ever be more than two dollar signs wrapping any MathJax code.
For examples:

|Code        | Output                                                              |
| ---------- | ------------------------------------------------------------------- |
|`A`         | Normal Text `A`                                                     |
|`$A$`       | Inline Maths `A`                                                    |
|`$$A$$`     | Displaystyle Maths `A`                                              |
|`$$$A$$$`   | Displaystyle Maths containing `$A` and Normal Text `$`              |
|`$$$$A$$$$` | empty Displaystyle Maths, Normal Text `A`, empty Displaystyle Maths |

Also see [sandbox](https://chemistry.meta.stackexchange.com/revisions/4175/4) or [wayback machine](https://web.archive.org/web/20180828121337/https://chemistry.meta.stackexchange.com/revisions/4175/4) for examples.

> I tried this out. The problem is that - by the proposed logic - it is impossible to unwrap a single dollar sign after two or more dollar signs have been inserted.

I don't understand, I don't understand which logic was proposed. Also this is how the script currently works, and that's fine the way it is.

What should happen is the following, where there is one borderline example **&dagger;** that would be open for interpretation:

|Input    | Shortcut                      | Description | Output  |
|---------|-------------------------------|-------------|-------- |
|`A`      | <kbd>Alt</kbd> + <kbd>z</kbd> | wrap        | `$A$`   |
|`A`      | <kbd>Alt</kbd> + <kbd>c</kbd> | wrap        | `$$A$$` |
|`$A$`    | <kbd>Alt</kbd> + <kbd>z</kbd> | unwrap      | `A`     |
|`$A$`    | <kbd>Alt</kbd> + <kbd>c</kbd> | see below **&dagger;**     |      |
|`$$A$$`  | <kbd>Alt</kbd> + <kbd>z</kbd> | unwrap      | `$A$`   |
|`$$A$$`  | <kbd>Alt</kbd> + <kbd>c</kbd> | unwrap      | `A`     |
|`$$$A$$` | <kbd>Alt</kbd> + <kbd>z</kbd> | unwrap      | `$$A$$` |
|`$$$A$$` | <kbd>Alt</kbd> + <kbd>c</kbd> | unwrap      | `$A$`   |
| more `$`'s |   | unwrap 2 or more |  less `$`'s |

The borderline case is when there is already a dollar, and you press double dollarify. You will have to decide which one get's done.

|   |Input    | Shortcut                      | Description | Output  |
|---|---------|-------------------------------|-------------|-------- |
|**&dagger;**| `$A$`    | <kbd>Alt</kbd> + <kbd>c</kbd> | unwrap      | `A`     |
|**&dagger;**| `$A$`    | <kbd>Alt</kbd> + <kbd>c</kbd> | defacto unwrap, then wrap (as alternative) | `$$A$$` |

**Comment by GaurangTandon** [comment]
Fantastic feedback...thanks for that! The explanation about more than two dollar signs was also very helpful. I am quite sure then that I had misunderstood the initial issue.

Anyway...regarding the borderline case, initially I thought to insert two dollar sign pairs (on top of the existing pair), however, you're right that three dollar sign pairs make no sense. So, I think that option 2 - "defacto unwrap, then wrap (as alternative)" - would be better. Thoughts?
